### ISSUE TITLE
Error running npm start with Node 12.1.0

### ISSUE THREAD

**Issue by rhafner** [biotope/biotope-boilerplate#99]
## Expected behavior
When entering "npm start" the server should be fired up and I can view the start page.

## Actual behavior
I get an error message and the server is not started.

```
PS C:\...> npm start
> biotope@6.0.0 start C:\projects\vi\biotope-for-non-biotopers\biotope-boilerplate
> gulp serve

fs.js:27
const { Math, Object, Reflect } = primordials;
                                  ^
ReferenceError: primordials is not defined
    at fs.js:27:35
    at req_ (C:\projects\vi\biotope-for-non-biotopers\biotope-boilerplate\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\projects\vi\biotope-for-non-biotopers\biotope-boilerplate\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\projects\vi\biotope-for-non-biotopers\biotope-boilerplate\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
```

Probably caused by: "Gulp 3 is broken on Node 12"
https://github.com/gulpjs/gulp/issues/2324

## Steps to reproduce

  1. Install node version 12.1.0
  2. npm install -g npx
  3. npx @biotope/cli init
 4. goto project folder
5. npm start

## Specifications

  - Biotope Version: 6.0.0
  - Node Version: 12.1.0
  - Yarn Version: n/a
  - Operating System: Win 10
  - Browser & Version: n/a

**Comment by jurekbarth** [comment]
@rhafner biotope/build is based on gulp 3 which is no longer supported in node 12. For further information: https://github.com/gulpjs/gulp/issues/2324
